//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDialog.VWPTrainer {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class VWPTrainer {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.ListBox lbTrainers;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnDelete;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(VWPTrainer target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.ListBox @__BuildControllbTrainers() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            this.lbTrainers = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbTrainers";
            @__ctrl.SelectionMode = global::System.Web.UI.WebControls.ListSelectionMode.Single;
            @__ctrl.AutoPostBack = false;
            @__ctrl.Rows = 4;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputButton @__BuildControlbtnDelete() {
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputButton();
            this.btnDelete = @__ctrl;
            @__ctrl.ID = "btnDelete";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "button");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "javascript:showDialog()");
            @__ctrl.Value = "Remove Selected Trainers";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::CustomDialog.VWPTrainer.VWPTrainer @__ctrl) {
            global::System.Web.UI.WebControls.ListBox @__ctrl1;
            @__ctrl1 = this.@__BuildControllbTrainers();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnDelete();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<script type=\"text/javascript\">\r\n    var dialogConfirm, openDialog;\r\n    func" +
                    "tion showDialog() {\r\n        var selectedId = document.getElementById(\'");
                                          @__w.Write(lbTrainers.ClientID );

            @__w.Write(@"').value;
        var divDelete = document.getElementById(""divDelete"");
        divDelete.style.display = ""block"";
        dialogConfirm = {
            html: divDelete,
            title: 'Confirm Trainer Deletion',
            allowMaximize: true,
            showClose: true,
            width: 450,
            height: 200
        };
        openDialog = SP.UI.ModalDialog.showModalDialog(dialogConfirm);
    }

    function deleteTrainer() {
        this.TrainerId = document.getElementById('");
                                          @__w.Write(lbTrainers.ClientID );

            @__w.Write(@"').value;
        var ctx = new SP.ClientContext();
        var trList = ctx.get_web().get_lists().getByTitle('ITAcademyTrainers');
        this.Trainer = trList.getItemById(TrainerId);
        Trainer.deleteObject();
        ctx.executeQueryAsync(Function.createDelegate(this, this.onSuccess), Function.createDelegate(this, this.onFailed));
    }

    function onSuccess() {
        alert(""Trainer width ID "" + TrainerId + "" has been deleted"");
        hideDialog();
    }

    function onFailed(sender, args) {
        alert(""Error. Trainer could not be deleted "" + ""\n\n"" + args.get_message() + ""\n\n"" + args.get_stackTrace());
        hideDialog();
    }

    function doCancel() {
        hideDialog();
    }

    function hideDialog() {
        openDialog.close();
        window.location.reload(true);
    }
</script>

");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write(" <br /> <br />\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write(@"

<div id=""divDelete"" style=""display: none;"">
    <table style=""width:350px;"" cellpadding=""4"" cellspacing=""4"">
        <tr>
            <td colspan=""2"">
                Are you sure of deleting this trainer?
            </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
            <td align=""center"" style=""width:150px"">
                <input type=""button"" value=""Yes"" style=""width:125px;"" onclick=""deleteTrainer()"" />
            </td>
            <td align=""center"" style=""width:150px"">
                <input type=""button"" value=""No"" style=""width:125px;"" onclick=""doCancel()"" />
            </td>
        </tr>
    </table>
</div>");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
